### ISSUE TITLE
How exactly typescript compile code?

### ISSUE THREAD

**Issue by jurajkocan** [stefalda/react-localization#42]
Hi there, I am not sure if this is issue for you or just me doing something wrong. Maby you could hep me anyway :P
I am working with typescript.

```javascript
import LocalizedStrings from "react-localization";

export const strings = new LocalizedStrings({
    en: {
        ImageDescription: "Here choose your logo that will be displayed on index page",
    },
    sk: {
        ImageDescription: "Here choose your logo that will be displayed on index page",
    },
});

const myReource = strings.ImageDescription;
```
on the last line i get error ts error:
**[ts] Property 'ImageDescription does not exist on type 'LocalizedStringsMethods'.**

But as i seen your d.ts file it seems like logic bug. 

Thx for respond.

**Comment by OmarTawfik** [comment]
With TypeScript it is a little bit tricky. `LocalizedStrings` definition file ([here](https://github.com/stefalda/react-localization/blob/master/lib/LocalizedStrings.d.ts)) doesn't know (in advance) the type of keys you'll define. So I've a workaround to still use types safely in my project along the lines of:
```typescript
// en.ts
import {IStrings} from "strings";
export const enStrings: IStrings = {
    key1: "value1",
    key2: "value2"
};
```
```typescript
// es.ts
import {IStrings} from "strings";
export const esStrings: IStrings = {
    key1: "value1",
    key2: "value2"
};
```
```typescript
// strings.ts
import {enStrings} from "en";
import {esStrings} from "es";
import LocalizedStrings from "react-localization";
export interface IStrings {
    key1: string;
    key2: string;
}
export const strings: IStrings & LocalizedStrings= new LocalizedStrings({
    en: enStrings,
    es: esStrings
}) as any,
```
The last line has all the magic. Since you're casting `as any`, the compiler will not complain about type mismatch errors between the initialized `LocalizedStrings` and the type `IStrings & LocalizedStrings` you specified.
So, outside of this module, when you `import {strings} from "strings"`, you'll find all types working correctly as expected.

**Comment by stefalda** [comment]
Hi,
I've reviewed the definition file and now it seems to work... just update to version 0.13

This simple code in the .tsx file compiles and displays just fine:


```typescript
const strings = new LocalizedStrings({
  en: {
    message: 'Hello from TypeScript',
    secondMessage: 'Hi, I\'m the second message',
    page2: {
        firstLabel: 'Hello'
    }
  }
}); 
```

**Comment by stefalda** [comment]
I've modified the typescript definitions and find a solution to have working autocomplete.

So this is suggested solution to work with typescript:

```js
export interface IStrings extends LocalizedStringsMethods{
    score:string;
    time: String;
}

public strings: IStrings;
this.strings = new LocalizedStrings({
            it: {
                score: "Punti",
                time: "Tempo"
            },
            en: {
                score: "Score",
                time: "Time"
            }
        });

```
