### ISSUE TITLE
formatString isn't working

### ISSUE THREAD

**Issue by tinmar33** [stefalda/react-localization#78]
Hello,
It seems that formatString isn't working. When i'm trying to replace '{0}' with juste a simple string, my navigator is displaying '{0}'

localization.js
```
const strings = new LocalizedStrings({
  FR,
  EN
});

strings.formatString(strings.search.placeholder, 'test')

export default strings
```

en.js (same as fr.js)
```
export default {
  search: {
    placeholder: 'test {0}',
  },
}
```

Is there a solution ?

**Comment by nightblade9** [comment]
For anyone else who stumbles on this, I, too, found the documentation misleading. The answer is: `strings.formatstring(string, param1, param2, ...0` returns the formatted string, it doesn't modify the data/collection inline.

Meaning, instead of doing this:

```typescript
let strings = { "en": { "test": "test {0} {0}" } }
strings.formatString(strings.test, "hi");
```

You should do this:

```typescript
const strings = ...
// ... elsewhere in markup
<p>Hello, {strings.format(strings.test, "world")}</p>
}
```

I don't know if this is the intended usage or not, but I tried all combinations of parameters/placeholders and this is the only thing that seems to work.

**Comment by stefalda** [comment]
_strings.format_ is just a function that returns the formatted string.
The formatted string is not replaced or changed in any way.
This is the intended use of the fuction.
